version: '3.7'
include:
  - proxy.yaml

volumes:
  db_mysql:

services:

  db:
    image: mysql:8
    restart: on-failure
    #env_file:
    # - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SQL_DATABASE}
      MYSQL_USER=: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker_volumes/mysql:/var/lib/mysql
    
    networks:
      backend:
        ipv4_address: 172.20.0.10

  web:
    build:
          dockerfile: Dockerfile.python
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_TABLE=requests
      - DB_USER=app
      - DB_NAME=virtd
      - DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      backend:
        ipv4_address: 172.20.0.5